module.exports={
	'HOME' : {
		SPOTIFY_SEARCH_COMPLETE:'SPOTIFY_SEARCH_COMPLETE',
		SET_HOME_DATA:'SET_HOME_DATA'
	},
	'PLAYLIST':{
		SET_PLAYLIST_DATA:'SET_PLAYLIST_DATA'
	},
	'SEARCH':{},
	'NOW_PLAYING':{}
}