module.exports={
	'HOME' : {
		SET_HOME_DATA:'SET_HOME_DATA'
	},
	'PLAYLIST':{
		SET_PLAYLIST_DATA:'SET_PLAYLIST_DATA',
		SET_INITIAL_PLAYLIST_DATA:'SET_INITIAL_PLAYLIST_DATA'
	},
	'SEARCH':{
		EDIT_SEARCH_KEY: 'EDIT_SEARCH_KEY',
		SPOTIFY_SEARCH_COMPLETE:'SPOTIFY_SEARCH_COMPLETE'
	},
	'PLAYER':{
		TOGGLE_PLAY:'TOGGLE_PLAY',
		START_PLAY:'START_PLAY'
	},
	'APP': {
		TOGGLE_LOGIN: 'TOGGLE_LOGIN'
	},
	'USER': {
		EDIT_CREDENTIALS: 'EDIT_CREDENTIALS',
		SUBMIT_CREDENTIALS: 'SUBMIT_CREDENTIALS'
	},
	'NOW_PLAYING':{
		ADD_TO_YT_QUEUE: 'ADD_TO_YT_QUEUE',
		ADD_TO_QUEUE:'ADD_TO_QUEUE',
		INCREMENT_INDEX:'INCREMENT_INDEX',
		RESET_QUEUE:'RESET_QUEUE',
		SET_INDEX:'SET_INDEX'
	}
}
