module.exports={
	'HOME' : {
		SET_HOME_DATA:'SET_HOME_DATA'
	},
	'PLAYLIST':{
		SET_PLAYLIST_DATA:'SET_PLAYLIST_DATA'
	},
	'SEARCH':{
		EDIT_SEARCH_KEY: 'EDIT_SEARCH_KEY',
		SPOTIFY_SEARCH_COMPLETE:'SPOTIFY_SEARCH_COMPLETE'
	},
	'NOW_PLAYING':{},
	'PLAYER':{
		TOGGLE_PLAY:'TOGGLE_PLAY',
		START_PLAY:'START_PLAY'
	}
}